# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VerticalPhotoPlacer
                                 A QGIS plugin
 This plugin places vertical drone photos on GIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-18
        copyright            : (C) 2020 by GIS center (IDEAS), Chubu University
        email                : ts18851-3009@sti.chubu.ac.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VerticalPhotoPlacer class from file VerticalPhotoPlacer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vertical_photo_placer import VerticalPhotoPlacer
    return VerticalPhotoPlacer(iface)
